config/routes.rb
Rails.application.routes.draw do
  resources :restaurants do
    resources :reviews, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  NAME = "chinese", "italian", "japanese", "french", "belgian"
  has_many :reviews, dependent: :destroy
  validates :address, :name, :category, presence: true
  validates :category, inclusion: { in: ["chinese", "italian", "japanese", "french", "belgian"] }
end

app/models/review.rb
class Review < ApplicationRecord
  RATING = 0, 1, 2, 3, 4, 5
  belongs_to :restaurant
  validates :rating, inclusion: { in: [0, 1, 2, 3, 4, 5] }
  validates :content, presence: true
  validates :rating, numericality: { only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :find_id, only: [:show, :edit, :update, :destroy]
  def index
    @restaurants = Restaurant.all
  end

  def show
    @review = Review.new
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.create(restaurant_params)
    if @restaurant.save
      redirect_to restaurants_path
    else
      render :new
    end
  end

  def edit; end

  def update
    if @restaurant.update(restaurant_params)
      redirect_to restaurants_path(@restaurants)
    else
      render :new
    end
  end

  def destroy
    @restaurant.destroy
    redirect_to restaurants_path
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end

  def find_id
    @restaurant = Restaurant.find(params[:id])

  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def show
    @reviews = Review.find(params[:id])
    @review.all
  end

  def new
    @restaurant = Restaurant.find(params[:id])
    @review = Review.new
  end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    @review.save
  end


  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end

  def restaurant_params
    params.require(:restaurant, :review).permit(:name, :address, :phone_number, :category, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- app/views/layouts/application.html.erb -->

    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <!-- Add these line for detecting device width -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

  <!-- [...] -->
  <%= javascript_include_tag "application" %> <!-- from app/assets/javascripts/application.js -->
  <%= javascript_pack_tag "application" %>    <!-- from app/javascript/packs/application.js -->
</body>

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/destroy.html.erb
<h1>Restaurants#destroy</h1>
<p>Find me in app/views/restaurants/destroy.html.erb</p>

app/views/restaurants/edit.html.erb
<h1><%= @restaurant.name %></h1>
<div>
  <%= simple_form_for @restaurant do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :phone_number %>
  <%= f.input :category %>
  <%= f.button :submit %>
<% end %>

</div>

<%= link_to "back", restaurants_path(@restaurants)%>

app/views/restaurants/index.html.erb
<h1>Rio's Restaurants</h1>
<p><strong>The best selection in the world!</strong></p>
<div><%= link_to "Create new restaurant", new_restaurant_path(@restaurant), class: "btn btn-ghost"%></div>


  <div class="container">
  <% @restaurants.each do |restaurant| %>
    <p><strong><%= link_to restaurant.name, restaurant_path(restaurant)%></strong></p>
    <ul>
      <li> <p><%= restaurant.address %></p></li>
      <li> <p><%= restaurant.phone_number %></p></li>
      <li> <p><%= restaurant.category %></p></li>
    </ul>
  <%end %>
  </div>

app/views/restaurants/new.html.erb
<h1>New restaurant</h1>
<div>
  <%= simple_form_for @restaurant do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :phone_number %>
  <%= f.input :category, as: :select, collection: Restaurant::NAME %>
  <%= f.button :submit %>
<% end %>

</div>


<%= link_to "back", restaurants_path(@restaurants)%>

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name %></h1>

    <ul = class="container">
      <li> <p><%= @restaurant.address %></p></li>
      <li> <p><%= @restaurant.phone_number %></p></li>
      <li> <p><%= @restaurant.category %></p></li>
      <img src="" alt="">
    </ul>

    <%= @restaurant.reviews.each do |review| %>
    <ul>
      <%= review.content %>
      <%= review.rating %>
    </ul>
    <% end %>

    <%= simple_form_for [@restaurant, @review] do |f| %>
    <%= f.input :content %>
    <%= f.input :rating, as: :select, collection: Restaurant::RATING %>
    <%= f.button :submit %>
    <% end %>


<div>
<%= link_to "delete", restaurant_path(@restaurant)%>
<%= link_to "update", edit_restaurant_path(@restaurant)%>
<%= link_to "back", restaurants_path(@restaurants)%>
</div>